[project]
name = "ErisPulse-Takumi"
version = "1.2.0"
description = "Use takumi-py to quickly render images."
readme = "README.md"
requires-python = ">=3.10"
license = "GPL-3.0-or-later"
authors = [ { name = "ccd2s", email = "tasaedem@outlook.com" } ]

dependencies = [
    "takumi-py>=0.3.0",
    "ErisPulse>=2.7.0-dev.0",
    "ErisPulse-PluginTakumi-Builtin-Fonts==1.1.0"
]

[project.urls]
"homepage" = "https://github.com/ccd2s/erispulse-plugin-takumi"

[project.entry-points]
"erispulse.module" = { "Takumi" = "Takumi:Main" }

[tool.setuptools]
packages = ["Takumi"]
